name: Brakujące / nieaktualne notatki
description: Zgłoś brakujące zajęcia, błąd merytoryczny albo nieaktualną treść notatki.
labels: [content]
body:
  - type: input
    id: course
    attributes:
      label: Przedmiot / semestr
      placeholder: np. Semestr 1 / Sieci komputerowe
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Co jest brakujące lub nieaktualne?
      description: Opisz czego dotyczy zgłoszenie, brakujące zajęcia, błąd w treści, nieaktualna informacja z sylabusu itd.
    validations:
      required: true
